# Generated by Django 4.2.6 on 2024-02-14 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0189_inbound_hop_nodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowjob',
            name='enable_prompt_nodes_job_type',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workflowjobtemplate',
            name='enable_prompt_nodes_job_type',
            field=models.BooleanField(default=False),
        ),
    ]
