# Generated by Django 4.2.6 on 2024-02-15 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0190_workflowjob_enable_prompt_nodes_job_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workflowjob',
            old_name='enable_prompt_nodes_job_type',
            new_name='ask_nodes_job_type_on_launch',
        ),
        migrations.RenameField(
            model_name='workflowjobtemplate',
            old_name='enable_prompt_nodes_job_type',
            new_name='ask_nodes_job_type_on_launch',
        ),
    ]
